### Créer un produit
POST {{baseUrl}}/admin/jewels
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

name=Chloé

### Uploader des images sur un produit
@jewelId=6a225da7ae80b0e0d7f8b0c0
POST {{baseUrl}}/admin/jewels/{{jewelId}}/images
Authorization: Basic {{adminCredentials}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="chloé_collier.jpg"
Content-Type: image/jpeg

< /home/noynto/Téléchargements/chloe_collier.jpg
--boundary--
#< ../docs/collier5.jpg

### Lister les IDs de produits (page HTML)
GET http://localhost:8080/jewels
Accept: text/html

### Charger la card d'un produit (fragment HTMX)
GET http://localhost:8080/jewels/{{jewelId}}/card
Accept: text/html

### Mettre à jour l'accroche d'un produit
PATCH {{baseUrl}}/admin/jewels/{{jewelId}}/tagline
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

tagline=Un bijou pensé pour celles qui aiment les pièces uniques, solaires et pleines de caractère.

### Mettre à jour le prix d'un produit
PATCH {{baseUrl}}/admin/jewels/{{jewelId}}/price
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

price=33.00

### Mettre à jour la catégorie d'un produit
PATCH {{baseUrl}}/admin/jewels/{{jewelId}}/category
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

category=NECKLACE

### Mettre à jour l'état d'un produit
PATCH {{baseUrl}}/admin/jewels/{{jewelId}}/state
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

state=PUBLISHED

### Télécharger une image
@imageId = variable value
GET http://localhost:8080/images/{{imageId}}