### Créer un produit
POST {{baseUrl}}/admin/products
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

name=Léa

### Uploader des images sur un produit
@productId=6a21e97c225e2b2fd3518fd5
POST {{baseUrl}}/admin/products/{{productId}}/images
Authorization: Basic {{adminCredentials}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="images"; filename="lea_collier.jpg"
Content-Type: image/jpeg

< /home/noynto/Téléchargements/lea_collier_small.jpg
--boundary--
#< ../docs/collier5.jpg

### Lister les IDs de produits (page HTML)
GET http://localhost:8080/products
Accept: text/html

### Charger la card d'un produit (fragment HTMX)
GET http://localhost:8080/products/{{productId}}/card
Accept: text/html

### Mettre à jour l'accroche d'un produit
PATCH {{baseUrl}}/admin/products/{{productId}}/tagline
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

tagline=Un bijou pensé pour celles qui aiment la douceur et la féminité.

### Mettre à jour le prix d'un produit
PATCH {{baseUrl}}/admin/products/{{productId}}/price
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

price=33.00

### Mettre à jour la catégorie d'un produit
PATCH {{baseUrl}}/admin/products/{{productId}}/category
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

category=NECKLACE

### Mettre à jour l'état d'un produit
PATCH {{baseUrl}}/admin/products/{{productId}}/state
Authorization: Basic {{adminCredentials}}
Content-Type: application/x-www-form-urlencoded

state=PUBLISHED

### Télécharger une image
@imageId = variable value
GET http://localhost:8080/images/{{imageId}}