apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - mongodb.yaml
  - mongodb-secret.yaml
  - mongodb-initdb-configmap.yaml